### ISSUE TITLE
Workflow doubt

### ISSUE THREAD

**Issue by lagden** [requirejs/alameda#14]
I was reading that is possible using `r.js` with `alameda`.

If I developing using **alameda** and when I optimize using `r.js` + `almond` the code generated will be compatible with IE 9+?

Was I clear enough?

Tks!

**Comment by jrburke** [comment]
[alameda](https://github.com/requirejs/alameda#alameda) cannot support IE9 due to no native promise support, and for only supporting browsers that properly trigger script onload events after the script is evaluated, so that means IE 10+.

IE 10 and 11 do not have native promise support. Those browsers can be supported via [alameda-prim](https://github.com/requirejs/alameda-prim).

But IE9 is not supported by alameda. Closing as a discussion ticket, feel free to continue discussion here.

**Comment by lagden** [comment]
Ok, I understood!
So, It's possible optimize `alameda` using **r.js** + **almond**?

**Comment by jrburke** [comment]
the r.js optimizer can be used with a project that uses alameda. If you want to build a set of files into one file and use almond as the AMD API, that should also work, and in that case almond would be used after the build instead of alameda.

**Comment by lagden** [comment]
Thank you for the explanation!
