### ISSUE TITLE
Performance Comparison

### ISSUE THREAD

**Issue by EisenbergEffect** [requirejs/alameda#15]
@jrburke First, it's great to see you working on this. The Durandal community has been very happy and very successful with RequireJS over the years.

For Aurelia, we started by using SystemJS since it was aligning with the upcoming Loader spec. However, after a year of building and writing apps with Aurelia, we've found that SystemJS is far slower than RequireJS. In fact many of the load issues that were initially attributed to Aurelia were bugs or perf problems in SystemJS, not our own code.

I'm bringing this up because I'm curious to see if you've done any performance comparisons with RequireJS and/or SystemJS. We are looking to move our Aurelia community towards an npm workflow for package management (rather than jspm) and we are looking for a loader that will play nice with that. We were going to move back to RequireJS for the reasons above. If alameda is the way forward, that might be the direction we want to take our community...but we don't want to steer them towards something that has the same issues as SystemJS.

Can you shed any light on performance at this point? Also, I'd love to hear if/how this might align with the Loader spec being worked on.

Thanks for all the work you've done over the years. We couldn't have done it without RequireJS!

**Comment by jrburke** [comment]
Hi @EisenbergEffect!

I have not done any perf comparisons with SystemJS. For me, trying to guess where the loader spec is going, trying to do an implementation that people use in production products, seems premature given that the spec is not done.

Over the many years, it has been hard to know where the loader spec was going because it has changed significantly over time, and the design process on it has been opaque. So I am resigned to just wait until they feel like they have something complete. That likely means that it could be different enough and their prototype loaders will be first movers in the space that it would make sense to just start using those tools at that time. But I expect it still to be a drawn out process.

As for specific performance profiling, I did a little bit of tuning of alameda when it was used in some Firefox OS apps. There was one app that said requirejs was just a little bit faster on startup than alameda, but that was before I did a couple of small tweaks in alameda, and I cannot recall if the native promise support in Firefox at that time was fully tuned. Unfortunately I did not redo the comparison as the work goals changed.

It should be really easy to swap between requirejs and alameda, just swapping the files for one another. So it should be possible to get good comparisons if you have a larger app that is a good example profile to use for performance.

Some things to note:

If using npm as the package manager, I suggest flat dependency install/dedupe, and using [adapt-pkg-main](https://github.com/jrburke/adapt-pkg-main) to create main module adapters in the node_modules directory, to avoid the need for large package config blocks for the loader. 

However if you want things to run in node, do server side rendering, you might have some issues around mismatches in module formats. If using webpack, maybe this is less of a concern, let it prep and convert the code for browser use.

alameda is more aggressive about a browser baseline: native promise support. alameda-prim ships a promise shim inside of it, which can support IE10 and IE11, but because of non-conforming script load event behavior in IE below IE10, only IE10 and above could possibly be targeted.

Because alameda relies on native promise support, you could see some perf differences across browsers if they have not tuned how they use a micro task queue.

alameda does not pass some of the requirejs tests. Basically, requirejs.undef and onResourceLoad tests because they are not implemented at the moment.

AMD loader support work is a background task for me. It is almost guaranteed that I will not be using these tools as part of my day job work. So my engagement will be diminished even more because of that.

Closing this as a discussion ticket, but please feel free to continue discussion here.

**Comment by EisenbergEffect** [comment]
Thanks for taking the time for such a detailed response. I share your opinion regarding the Loader spec. I had hoped when I started on Aurelia 18 months ago that things would be worked out by now...but it seems to me we may not even be close. We wanted Aurelia to support as many loaders as we could, so this doesn't affect Aurelia's core fortunately (We already had built-in support for require.js/dojo and we've recently been working on Webpack).

Really, for us, it's mostly a matter of how we want to guide the community today. It sounds like RequireJS is probably still the best option, but it shouldn't be hard for us to support both it and alameda in Aurelia.

Thanks for the tip about adapt-package-main. We are looking for ways to make using npm with require.js and Aurelia as smooth of a process as possible. We've got our `aurelia-bundler` which takes our own config and automates the system.js builder. We think it can easily be taught to also generate r.js config and automate that tool based on our needs. adapt-package-main might help us on the other side of things. We'll find out soon enough ;)

All in all, I'm feeling a bit relieved about returning to RequireJS. As a framework builder...I've had a lot of stress from the whole Loader spec and SystemJS experience. I built some amazing stuff with RequireJS in the past and I know that it works. We have Durandal apps built with RequireJS with 100k+ LOC and the companies that have built those have been really happy.

Keep up the great work! We'll check out adapt-package-main and see how that works. If need be, our team can collaborate on improving tools to integrate the npm/require.js workflow.
