### ISSUE TITLE
Integrated Transpilation

### ISSUE THREAD

**Issue by EisenbergEffect** [requirejs/alameda#17]
Does alameda support any hooks which would enable on-the-fly-transpilation using Babel or TypeScript? If so, does requirejs also have similar hooks? If not, could it be patched in? Would you be interested in such a contribution?

**Comment by jrburke** [comment]
requirejs has a [requirejs.load](https://github.com/requirejs/requirejs/blob/3b5407eb9daa3964eaec1132f225805bcc347e77/require.js#L1882) that can be overridden to do XHR fetching and code translation. [cajon](https://github.com/requirejs/cajon) uses that hook to [support XHR loading of CJS modules](https://github.com/requirejs/cajon/blob/7f1008b861f7de6be25abcff3141b83cd4c42d4e/tools/c.js#L177).

alameda does not have that hook exposed at the moment. However, I have recently been thinking of allowing overrides of `normalize` and `nameToUrl` (although maybe under a different name, like `locate`) by passing in some lifestyle config to requirejs.config(), so I can see where allowing a `load` override might also make sense.

I was just in initial research phase for it, and want to study the cost some more. I want to evaluate it within in the next week. If I can get it to not be too invasive or expose too much internal state, then I may want to also port that back to requirejs, since the optimizer would likely want to be able to use the same overrides for building.

**Comment by EisenbergEffect** [comment]
@jrburke This is excellent. I actually have two use cases.

1. Handle both AMD and CommonJS modules transparently.
2. Integrate Babel and TypeScript transpile for certain well-known scenarios/modules.

It sounds like cajon will handle the first scenario. Is that correct? I haven't heard of it before, but I'm seeing lately that you've built quite a few loader variants. Has cajon been used in production? or is it more of an experiment? Does it have pretty good performance?

**Comment by jrburke** [comment]
cajon uses the stock requirejs as a base and just injects the requirejs.load() override. You could use the same approach if you wanted to do something more in the load step if wanting to use something today.

As far as performance, the only diff would be the hit for doing XHR + eval (and the related CORS/CSP constraints with those) vs the script tag loading. cajon has been around for a while, at least 2 years. I just keep the version number small out of old habit, and because I do not want to support people that do not understand the issues that can occur with XHR+eval.

As for r.js, internally it uses require.js stock to do the tracing, but the optimizer supports a [cjsTranslate](https://github.com/requirejs/r.js/blob/master/build/example.build.js#L579) option that can wrap CommonJS files in a define() wrapper so that they work with the optimizer. Note that it just adds a define() wrapper, supports __filename and __dirname, but does not try to do any other shimming like Node's `process` or `global`.

**Comment by EisenbergEffect** [comment]
Ok, would you recommend I introduce a build step to convert commonjs modules then? It sounds like that would be more performant and less constrained. Does the r.js cjsTranslate find require calls within the module and surface those into the define's dependency list? Is it possible to use this outside of a full r.js optimization pass? I think I saw docs on this but it wasn't clear whether it simply added a define wrapper or if it also surfaced the dependencies.

**Comment by jrburke** [comment]
If you have a build step that does transpiling, then just converting to AMD modules as part of that step will be the most portable.

The define() wrapping can be called separately:
https://github.com/requirejs/r.js#convert-commonjs-modules

Although, if you do have a transpiler in play, I believe the ones like babel/webpack have AMD output options.

The cjsTranslate just adds `define(function(require, exports, module) { /* cjs code here */ })`, a bit more than that if __filename or __dirname is used. That is basically the [sugared syntax](http://requirejs.org/docs/whyamd.html#sugar) for AMD modules, and the optimizer knows how to trace the factory functions for require(String) use and build up the dependency array for tracing/output.

**Comment by EisenbergEffect** [comment]
I've got a build system in play. So, it makes sense to extend that with the conversion code. Thanks for all the assistance! I'll close this issue and follow up with any questions if I encounter issues using the r.js apis to achieve the desired output.

On that note, there used to be a google group. I didn't see the link to that on the site. Should I be posting questions here or would you prefer them go elsewhere? I noted the use of SO but wasn't sure if that would be the best place for this particular type of inquiry.

**Comment by jrburke** [comment]
Right, I changed the link on the website to point to Stack Overflow because the vast majority of questions were people needing more basic help in setting up their projects. Something that Stack Overflow is better equipped to handle, since I was not answering them on the group list. I do not look at the Stack Overflow questions either, but hopefully there are people over there more incentivized to answer.

Your questions are more from an integrator side of things, you know the basics already, and so using a github issue is fine with me.
